# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test Github secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: |
        echo "the Github secret will be unmasked"
        echo ${{ secrets.SECRET_TOKEN }} | sed 's/ ./& /g'
        
        

